### ISSUE TITLE
push時にNext.jsをビルド

### ISSUE THREAD

**Issue by shun-harutaro** [NittcWind/official_site#10]

**Comment by ssssota** [comment]
https://github.com/ssssota/hololive-music.web.app/tree/51d0260244e780354b0af0d7e5fd8e6bdcd068c8/.github/workflows
この辺り参考になるかも
Svelte使ってるけどやってることは概ね同じ。ビルドしてfirebaseにデプロイしてる。

PRでプレビュー環境立てるやつもある

**Comment by shun-harutaro** [comment]
なるほど、自分で用意するのもありですね。`ssssota/setup-firebase-tools@v1`
